#version: '3.8'
#
#services:
#  zookeeper:
#    image: wurstmeister/zookeeper:latest
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: wurstmeister/kafka:latest
#    container_name: kafka
#    ports:
#      - "9093:9093"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
#      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9093
#    depends_on:
#      - zookeeper
#
##      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
##      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
##      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
##      KAFKA_LISTENER_NAMES: INSIDE
##      KAFKA_LISTENER_INTERNAL: INSIDE://kafka:9093
##      KAFKA_LISTENER_PORT: 9093
##      KAFKA_LISTENER_HOSTNAME: kafka
##      KAFKA_LISTENER_INTERNAL_PORT: 9093
##    depends_on:
##      - zookeeper
##    networks:
##      - kafka_network
##
##networks:
##  kafka_network:
##    driver: bridge



networks:
  kafka-network:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:5.5.2
    environment:
        KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT  # Default security protocol
        KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
        KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT  # Defining protocols for both listeners
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - kafka-network
